### ISSUE TITLE
Learn to write documentation

### ISSUE THREAD

**Issue by Mostalk** [coutaq/img2pdf#1]
In the First, you have not indicated anywhere how and where to create a bot token and that it needs to be shoved into the TOKEN file
Secondly, "Installation" - is there enough initialization? No, this will not work. The bot should be turned on.

**Comment by coutaq** [comment]
You do not need to create any bot tokens or shove anything into any file. 
To use the bot, simply use this link _http://t.me/img2pdfpy_bot_ to initialize the bot, that's it!
